import type { CardType } from "./types";

export const CARD_TEMPLATES: CardType[] = [
  {
    slug: "amex_platinum",
    name: "Amex Platinum",
    defaultAnnualFee: 895,
    color: "#8E9EAF",
    defaultBenefits: [
      {
        name: "$300 Hotel Credit FHR/THC (H1)",
        description: "Fine Hotels + Resorts or The Hotel Collection credit, January–June",
        faceValue: 300,
        category: "hotel",
        resetType: "calendar",
        resetConfig: { period: "semi_annual", applicableMonths: [1, 2, 3, 4, 5, 6] },
      },
      {
        name: "$300 Hotel Credit FHR/THC (H2)",
        description: "Fine Hotels + Resorts or The Hotel Collection credit, July–December",
        faceValue: 300,
        category: "hotel",
        resetType: "calendar",
        resetConfig: { period: "semi_annual", applicableMonths: [7, 8, 9, 10, 11, 12] },
      },
      {
        name: "$200 Airline Fee Credit",
        description: "Annual airline fee credit for selected airline",
        faceValue: 200,
        category: "airline",
        resetType: "calendar",
        resetConfig: { period: "annual" },
      },
      {
        name: "$200 Oura Ring Credit",
        description: "Annual Oura Ring membership credit",
        faceValue: 200,
        category: "wellness",
        resetType: "calendar",
        resetConfig: { period: "annual" },
      },
      {
        name: "$209 CLEAR+ Credit",
        description: "Annual CLEAR Plus membership credit",
        faceValue: 209,
        category: "travel",
        resetType: "subscription",
        resetConfig: {},
      },
      {
        name: "$100 Global Entry / TSA PreCheck",
        description: "Global Entry or TSA PreCheck application fee credit",
        faceValue: 100,
        category: "travel",
        resetType: "calendar",
        resetConfig: { period: "every_4_years" },
      },
      {
        name: "$100/quarter Resy Dining Credit",
        description: "Quarterly dining credit at Resy restaurants",
        faceValue: 100,
        category: "dining",
        resetType: "calendar",
        resetConfig: { period: "quarterly" },
      },
      {
        name: "$75/quarter Lululemon Credit",
        description: "Quarterly Lululemon credit",
        faceValue: 75,
        category: "shopping",
        resetType: "calendar",
        resetConfig: { period: "quarterly" },
      },
      {
        name: "$25/mo Digital Entertainment",
        description: "Monthly digital entertainment credit",
        faceValue: 25,
        category: "streaming",
        resetType: "subscription",
        resetConfig: {},
      },
      {
        name: "$15/mo Uber Cash (Jan-Nov)",
        description: "Monthly Uber Cash credit, January–November",
        faceValue: 15,
        category: "transportation",
        resetType: "calendar",
        resetConfig: { period: "monthly", applicableMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] },
      },
      {
        name: "$35 Uber Cash (Dec)",
        description: "December Uber Cash credit (bonus month)",
        faceValue: 35,
        category: "transportation",
        resetType: "calendar",
        resetConfig: { period: "monthly", applicableMonths: [12] },
      },
      {
        name: "$120/yr Uber One Membership",
        description: "Annual Uber One membership credit",
        faceValue: 120,
        category: "transportation",
        resetType: "subscription",
        resetConfig: {},
      },
      {
        name: "$12.95/mo Walmart+",
        description: "Monthly Walmart+ membership credit",
        faceValue: 12.95,
        category: "shopping",
        resetType: "subscription",
        resetConfig: {},
      },
    ],
  },
  {
    slug: "amex_aspire",
    name: "Hilton Aspire",
    defaultAnnualFee: 550,
    color: "#1A5276",
    defaultBenefits: [
      {
        name: "$200 Hilton Resort Credit (H1)",
        description: "Hilton resort credit, January–June",
        faceValue: 200,
        category: "hotel",
        resetType: "calendar",
        resetConfig: { period: "semi_annual", applicableMonths: [1, 2, 3, 4, 5, 6] },
      },
      {
        name: "$200 Hilton Resort Credit (H2)",
        description: "Hilton resort credit, July–December",
        faceValue: 200,
        category: "hotel",
        resetType: "calendar",
        resetConfig: { period: "semi_annual", applicableMonths: [7, 8, 9, 10, 11, 12] },
      },
      {
        name: "$50/quarter Flight Credit",
        description: "Quarterly airline credit",
        faceValue: 50,
        category: "airline",
        resetType: "calendar",
        resetConfig: { period: "quarterly" },
      },
      {
        name: "$209 CLEAR+ Credit",
        description: "Annual CLEAR Plus membership credit",
        faceValue: 209,
        category: "travel",
        resetType: "subscription",
        resetConfig: {},
      },
      {
        name: "Free Weekend Night Award",
        description: "Annual free weekend night certificate at Hilton properties",
        faceValue: 0,
        category: "hotel",
        resetType: "anniversary",
        resetConfig: {},
      },
      {
        name: "$100 Waldorf/Conrad Credit",
        description: "Credit at Waldorf Astoria or Conrad properties per stay",
        faceValue: 100,
        category: "hotel",
        resetType: "since_last_use",
        resetConfig: { cooldownDays: 0 },
      },
    ],
  },
  {
    slug: "chase_sapphire_preferred",
    name: "Chase Sapphire Preferred",
    defaultAnnualFee: 95,
    color: "#2471A3",
    defaultBenefits: [
      {
        name: "$50 Annual Hotel Credit",
        description: "Annual hotel credit through Chase Travel",
        faceValue: 50,
        category: "hotel",
        resetType: "anniversary",
        resetConfig: {},
      },
      {
        name: "$10/mo DashPass Promo Credit",
        description: "Monthly DoorDash promotional credit",
        faceValue: 10,
        category: "dining",
        resetType: "calendar",
        resetConfig: { period: "monthly" },
      },
      {
        name: "DashPass Membership ($120/yr value)",
        description: "Annual DashPass membership included",
        faceValue: 120,
        category: "dining",
        resetType: "subscription",
        resetConfig: {},
      },
    ],
  },
  {
    slug: "chase_sapphire_reserve",
    name: "Chase Sapphire Reserve",
    defaultAnnualFee: 795,
    color: "#1A1A2E",
    defaultBenefits: [
      {
        name: "$300 Annual Travel Credit",
        description: "Annual travel credit applied automatically",
        faceValue: 300,
        category: "travel",
        resetType: "anniversary",
        resetConfig: {},
      },
      {
        name: "$250 The Edit Hotel Credit",
        description: "Annual credit at The Edit hotel collection",
        faceValue: 250,
        category: "hotel",
        resetType: "calendar",
        resetConfig: { period: "annual" },
      },
      {
        name: "$250 Select Hotel Credit",
        description: "Annual credit at Select hotel properties",
        faceValue: 250,
        category: "hotel",
        resetType: "calendar",
        resetConfig: { period: "annual" },
      },
      {
        name: "$150 Exclusive Tables Dining (H1)",
        description: "Exclusive Tables dining credit, January–June",
        faceValue: 150,
        category: "dining",
        resetType: "calendar",
        resetConfig: { period: "semi_annual", applicableMonths: [1, 2, 3, 4, 5, 6] },
      },
      {
        name: "$150 Exclusive Tables Dining (H2)",
        description: "Exclusive Tables dining credit, July–December",
        faceValue: 150,
        category: "dining",
        resetType: "calendar",
        resetConfig: { period: "semi_annual", applicableMonths: [7, 8, 9, 10, 11, 12] },
      },
      {
        name: "$120 Global Entry / TSA PreCheck",
        description: "Global Entry or TSA PreCheck application fee credit",
        faceValue: 120,
        category: "travel",
        resetType: "calendar",
        resetConfig: { period: "every_4_years" },
      },
      {
        name: "$25/mo DoorDash Promo",
        description: "Monthly DoorDash promotional credit",
        faceValue: 25,
        category: "dining",
        resetType: "calendar",
        resetConfig: { period: "monthly" },
      },
      {
        name: "DashPass Membership ($120/yr value)",
        description: "Annual DashPass membership included",
        faceValue: 120,
        category: "dining",
        resetType: "subscription",
        resetConfig: {},
      },
      {
        name: "$10/mo Peloton Membership",
        description: "Monthly Peloton membership credit",
        faceValue: 10,
        category: "wellness",
        resetType: "subscription",
        resetConfig: {},
      },
      {
        name: "$5/mo DoorDash Credit",
        description: "Monthly DoorDash credit",
        faceValue: 5,
        category: "dining",
        resetType: "calendar",
        resetConfig: { period: "monthly" },
      },
    ],
  },
  {
    slug: "chase_marriott_boundless",
    name: "Chase Marriott Boundless",
    defaultAnnualFee: 95,
    color: "#6B2D5B",
    defaultBenefits: [
      {
        name: "Free Night Award (up to 35k pts)",
        description: "Annual free night certificate at Marriott properties",
        faceValue: 0,
        category: "hotel",
        resetType: "anniversary",
        resetConfig: {},
      },
      {
        name: "$50 Airline Credit (H1 2026)",
        description:
          "2026 promotional airline credit (H1), requires $250+ airline spend",
        faceValue: 50,
        category: "airline",
        resetType: "one_time",
        resetConfig: { expiresDate: "2026-06-30" },
      },
      {
        name: "$50 Airline Credit (H2 2026)",
        description:
          "2026 promotional airline credit (H2), requires $250+ airline spend",
        faceValue: 50,
        category: "airline",
        resetType: "one_time",
        resetConfig: { expiresDate: "2026-12-31" },
      },
      {
        name: "15 Elite Night Credits",
        description: "Annual Marriott Bonvoy elite night credits",
        faceValue: 0,
        category: "hotel",
        resetType: "calendar",
        resetConfig: { period: "annual" },
      },
    ],
  },
];
